[package]
name = "anonymizer"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
description = "GDPR-complient Kafka-to-ClickHouse ETL pipeline for HTTP logs"
repository = "https://github.com/matyama/http-log-anonymizer"
edition = "2021"
# TODO: license metadata
build = "build.rs"

[lib]
name = "anonymizer"
path = "src/lib.rs"

[[bin]]
name = "anonymizer"
path = "src/main.rs"

[dependencies]
# TODO: https://github.com/vertexclique/callysto/blob/master/Cargo.toml#L46
callysto = { version = "0.1", features = ["tokio"] }
capnp = "0.15"
clickhouse = { version = "0.11", features = ["time"] }
config = "0.13"
itertools = "0.10"
serde = { version = "1.0", features = ["derive"] }
time = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
capnpc = "0.15"

[dev-dependencies]
rstest = "0.16"

