[package]
name = "anonymizer"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
description = "GDPR-complient Kafka-to-ClickHouse ETL pipeline for HTTP logs"
repository = "https://github.com/matyama/http-log-anonymizer"
edition = "2021"
build = "build.rs"

[lib]
name = "anonymizer"
path = "src/lib.rs"

[[bin]]
name = "anonymizer"
path = "src/main.rs"

# TODO: rdkafka - add `features = ["dynamic-linking"] ` for `librdkafka` in Docker build

[dependencies]
anyhow = "1.0"
capnp = "0.15"
clickhouse-format = "0.2"
clickhouse-http-client = "0.1"
config = "0.13"
futures = "0.3"
# XXX: deprecate hyper?
hyper = { version = "0.14", features = ["client", "tcp", "http1", "stream", "server"] }
itertools = "0.10"
maplit = "1.0"
rdkafka = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
capnpc = "0.15"

[dev-dependencies]
rstest = "0.16"

