{
 "title": "Anonymizer / Performance",
 "tags": [
  "troubleshoot",
  "anonymizer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Anonymizer Host",
    "query": {
     "query": "label_values(anonymizer_pipeline_messages_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Log processing: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Message Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(anonymizer_pipeline_message_latency_seconds_sum{instance=~\"$instance\"}[5m])\n/\nrate(anonymizer_pipeline_message_latency_seconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} / Mean"
    },
    {
     "expr": "histogram_quantile(0.99, rate(anonymizer_pipeline_message_latency_seconds_bucket{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} / 99thPercentile"
    },
    {
     "expr": "histogram_quantile(0.75, rate(anonymizer_pipeline_message_latency_seconds_bucket{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} / 75thPercentile"
    }
   ]
  },
  {
   "title": "Messages Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anonymizer_pipeline_messages_total{instance=~\"$instance\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Processed bytes",
   "type": "gauge",
   "description": "Average ingested and processed message payload size in bytes over a minute",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(anonymizer_pipeline_message_payload_bytes{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inserted Total",
   "type": "stat",
   "description": "Total count of entries inserted to ClickHouse",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anonymizer_pipeline_output_inserted_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log count per level",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"anonymizer\"}[$__interval])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Output Entries",
   "type": "timeseries",
   "description": "Number of entries to output in the next insert(s) to ClickHouse",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "anonymizer_pipeline_output_entries{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Output Insert Block Occupation",
   "type": "gauge",
   "description": "The percentage of the capacity of the next block to insert into ClickHouse which has been used by insert entries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anonymizer_pipeline_output_insert_block_percent{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Output Time",
   "type": "timeseries",
   "description": "Time in seconds of issuing single insert to ClickHouse",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(anonymizer_pipeline_output_duration_seconds_sum{instance=~\"$instance\"}[5m])\n/\nrate(anonymizer_pipeline_output_duration_seconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} / Mean"
    },
    {
     "expr": "histogram_quantile(0.99, rate(anonymizer_pipeline_output_duration_seconds_bucket{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} / 99thPercentile"
    },
    {
     "expr": "histogram_quantile(0.75, rate(anonymizer_pipeline_output_duration_seconds_bucket{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} / 75thPercentile"
    }
   ]
  },
  {
   "title": "Queued Insert Blocks",
   "type": "gauge",
   "description": "Number of insert blocks in the output queue",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "anonymizer_pipeline_output_queued_blocks{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{app=\"anonymizer\"} | json"
    }
   ]
  }
 ]
}